import Head from 'next/head';
import { CardRedirect } from '../components/CardRedirect';
import { EssayEdit } from '../components/EssayEdit';
import { Layout } from '../components/Layout';
import * as S from '../styles/styles';
import { MdAddPhotoAlternate } from 'react-icons/md';
import { AiFillFileText } from 'react-icons/ai';
import { RiFileEditFill, RiImageEditFill } from 'react-icons/ri';

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <S.Container>
          <CardRedirect
            backgroundCard="var(--blueTwo-light)"
            title="Mandar sua redação por foto"
            content="Clique aqui!"
            icon={<MdAddPhotoAlternate />}
            link={'/send-image'}
          />
          <CardRedirect
            backgroundCard="var(--blueTwo-light)"
            title="Mandar sua redação digitada"
            content="Clique aqui!"
            icon={<AiFillFileText />}
            link={'/send-text'}
          />
          <CardRedirect
            backgroundCard="var(--blueTwo-light)"
            title="Corrigir redação por foto"
            content="Clique aqui!"
            icon={<RiImageEditFill />}
            link={'/correction-image'}
          />
          <CardRedirect
            backgroundCard="var(--blueTwo-light)"
            title="Corrigir redação digitada"
            content="Clique aqui!"
            icon={<RiFileEditFill />}
            link={'/correction-text'}
          />
        </S.Container>
      </Layout>
    </>
  );
}
