import Head from 'next/head';
import { EssayEdit } from '../components/EssayEdit';
import * as S from '../styles/styles';

export default function Home() {
  return (
    <S.Container>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <EssayEdit />
    </S.Container>
  );
}
